name: Default Variable Example Workflow
on: push
jobs:
  show-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display Default Workflow
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Actor: $GITHUB_ACTOR"
          echo "SHA: $GITHUB_SHA"
          echo "Event Name: $GITHUB_EVENT_NAME"
