name: Scheduled Push Event
on: 
  schedule:
    - cron: '*/5 * * * *' #every 5 minutes
jobs:
  show-info:
    runs-on: ubuntu-latest
    steps:
      - name: Scheduled Events
        run:
          echo "This is a scheduled event trigger for testing"
  
    
