name: node.js CI
on: push
jobs: # Start of the jobs
  build:
    runs-on: ubuntu-latest
    steps: #start of the build job section
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-nodejs@v4
        with:
          node-version: 14
      - name: Run Install
        run: npm install
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
  test:
    runs-on: ubuntu-latest
    steps: # start of the test job section
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-nodejs@v4
      - name: Run Install
        run: npm install
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
        
        
  
