name: Data Passing Workflow
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Data
        run: echo "Some data generated" > data.txt
      - name: Upload data as Artifact
        uses: actions/upload-artifact@v4
        with: 
          name: data-artifact
          path: data.txt
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Data from Artifactory
        uses: actions/download-artifact@v4
        with:
          name: data-artifact
          path: data/
      - name: Read Data in Job 2
        run: cat data/data.txt
